//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASTR
    {
        public decimal ID { get; set; }
        public Nullable<bool> TIPO { get; set; }
        public Nullable<bool> POS_UNO { get; set; }
        public Nullable<bool> POS_DOS { get; set; }
        public Nullable<bool> POS_TRES { get; set; }
        public Nullable<bool> POS_CUATRO { get; set; }
        public string SIGN { get; set; }
        public Nullable<int> NUM_SOR { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
    }
}
