CREATE USER userSort IDENTIFIED BY userSort;
GRANT RESOURCE TO userSort;
GRANT CREATE SESSION TO userSort;

CREATE TABLE ASTR(
	TIPO NUMBER(1),
	POS_UNO NUMBER(1),
	POS_DOS NUMBER(1),
	POS_TRES NUMBER(1),
	POS_CUATRO NUMBER(1), 
	SIGN VARCHAR2(15), 
	NUM_SOR NUMBER(6),
	FECHA DATE
	);